trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository'

steps:
  - task: Maven@4
    displayName: 'Compilar e testar com Maven (perfil dev)'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-Pdev -DskipTests=false'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'

  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
      path: $(HOME)/.m2/repository
    displayName: Cache Maven local repository

  - script: mkdir -p $(HOME)/.m2/repository
    displayName: Ensure .m2 directory exists

  - script: mvn -B clean package
    displayName: Build with Maven

  - task: Docker@2
    displayName: 'Build e Push da imagem Docker'
    inputs:
      containerRegistry: 'DockerHubConnection'
      repository: 'evandrossjr/dimonex'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        latest
        $(Build.BuildId)
