# H2 Connection
spring.datasource.url=jdbc:h2:file:../db-test/dinmonexdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.security=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL
#spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

# ===============================================
# CONFIGURA��ES DA AWS E DO SIMPLE EMAIL SERVICE (SES)
# ===============================================

# As suas credenciais do utilizador IAM que voc� criou.
spring.cloud.aws.credentials.access-key=SEU_ACCESS_KEY_ID_AQUI
spring.cloud.aws.credentials.secret-key=SEU_SECRET_ACCESS_KEY_AQUI

# A regi�o da AWS onde voc� configurou o SES.
# Verifique a sua regi�o na consola da AWS (ex: us-east-1, sa-east-1).
spring.cloud.aws.region.static=us-east-1

# E-mail do remetente. IMPORTANTE: Este e-mail deve ser verificado no seu painel do SES.
# Na consola da AWS, v� para SES -> Verified identities e verifique o seu e-mail.
cloud.aws.ses.from=seu-email-verificado@exemplo.com